#include "Ikonki.h"

const char *Ikonki::nowy[] = {
	/* columns rows colors chars-per-pixel */
	"32 32 134 2 ",
	"   c None",
	".  c black",
	"X  c #4A688D",
	"o  c #4B688F",
	"O  c #4C698F",
	"+  c #4D6A90",
	"@  c #4D6A91",
	"#  c #4F6B92",
	"$  c #4F6C91",
	"%  c #516E93",
	"&  c #516D94",
	"*  c #536F96",
	"=  c #537095",
	"-  c #557197",
	";  c #557198",
	":  c #57749A",
	">  c #5A769B",
	",  c #5A769C",
	"<  c #5C789E",
	"1  c #5C799E",
	"2  c #5E7AA0",
	"3  c #607CA2",
	"4  c #617DA3",
	"5  c #637FA5",
	"6  c #6681A7",
	"7  c #6682A8",
	"8  c #6884AA",
	"9  c #6A86AC",
	"0  c #6B87AC",
	"q  c #6D89AE",
	"w  c #6F8BB0",
	"e  c #708BB1",
	"r  c #728EB2",
	"t  c #728EB3",
	"y  c #7490B5",
	"u  c #7490B6",
	"i  c #7792B7",
	"p  c #7693B8",
	"a  c #7995BA",
	"s  c #7A95BA",
	"d  c #7C97BB",
	"f  c #7B96BC",
	"g  c #7E98BE",
	"h  c #7E99BE",
	"j  c #7F9ABF",
	"k  c #809AC0",
	"l  c #809BC0",
	"z  c #819DC1",
	"x  c #839EC3",
	"c  c #84A0C4",
	"v  c #86A1C6",
	"b  c #87A2C7",
	"n  c #88A3C7",
	"m  c #8DA5C7",
	"M  c #88A3C8",
	"N  c #89A3C8",
	"B  c #88A4C8",
	"V  c #89A4C8",
	"C  c #8EA7C8",
	"Z  c #8FA9C9",
	"A  c #91AACA",
	"S  c #A0B3CC",
	"D  c #A2B4CC",
	"F  c #A3B5CD",
	"G  c #A4B7CD",
	"H  c #A5B8CE",
	"J  c #A6B8CE",
	"K  c #A5B8D0",
	"L  c #ABBDD4",
	"P  c #B1C2D9",
	"I  c #B9C9DE",
	"U  c #BBCADE",
	"Y  c #BACBDE",
	"T  c #BCCBDF",
	"R  c #BDCCE0",
	"E  c #C0CDE0",
	"W  c #C0CEE1",
	"Q  c #C1D0E3",
	"!  c #C1D1E3",
	"~  c #C2D0E2",
	"^  c #C4D1E3",
	"/  c #C9D7E9",
	"(  c #CBD8EA",
	")  c #CBD9EA",
	"_  c #CFDAE9",
	"`  c #CCD8EA",
	"'  c #CCD9EA",
	"]  c #CCD9EB",
	"[  c #CDD9EB",
	"{  c #CCDAEB",
	"}  c #CEDBEB",
	"|  c #D0DCEC",
	" . c #D1DCEC",
	".. c #D0DDEC",
	"X. c #D2DEED",
	"o. c #D4DFEE",
	"O. c #D5DFEE",
	"+. c #D4E0EE",
	"@. c #D7E1EF",
	"#. c #D7E2EF",
	"$. c #D9E3F0",
	"%. c #DAE3F0",
	"&. c #DCE5F1",
	"*. c #DEE7F2",
	"=. c #DFE7F2",
	"-. c #E1E8F3",
	";. c #E3EAF4",
	":. c #E3EBF4",
	">. c #E4EAF4",
	",. c #E6EDF5",
	"<. c #E7EDF5",
	"1. c #EAEFF5",
	"2. c #EBEFF5",
	"3. c #E9EEF6",
	"4. c #E9EFF6",
	"5. c #EBF0F6",
	"6. c #EBF0F7",
	"7. c #EBF1F7",
	"8. c #ECF0F7",
	"9. c #ECF1F7",
	"0. c #EEF2F8",
	"q. c #EEF3F8",
	"w. c #F0F4F9",
	"e. c #F1F4F9",
	"r. c #F3F6FA",
	"t. c #F5F7FB",
	"y. c #F5F8FB",
	"u. c #F7F9FC",
	"i. c #F9FAFD",
	"p. c #F9FBFD",
	"a. c #FBFCFD",
	"s. c #FCFDFE",
	"d. c #FEFEFF",
	"f. c white",
	/* pixels */
	"      N V V M M N N M N N V V N B B N V M M b                   ",
	"      n f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.5.A                 ",
	"      v f.I P L K S S S S S S S S S S S S f.f.5.Z               ",
	"      c f./ / / / Q Q Q Q ! Q Q Q ! U Y S f.f.f.2.C             ",
	"      x f.( ) ( ( ` ( ( ` ( ' ( ( ( ( T D f.f.f.f.2.m           ",
	"      z f.] ] ] [ { ] [ { [ ] ] ] ] ] R F f.f.f.f.f.1.j         ",
	"      l f.} } } } } } } } } } } } } } E G f.f.f.f.f.f.k         ",
	"      g f.| | | | ..| | ..|  .| | | | W H H H J H H f.h .       ",
	"      f f.X.X.X.X.X.X.X.X.X.X.X.X.X.X.~ ~ ~ ~ ~ ~ ~ f.d .       ",
	"      s f.o.o.O.o.o.O.o.o.+.o.o.+.o.o.o.+.o.o.o.o.^ f.a .       ",
	"      p f.#.@.@.@.#.@.@.#.@.@.@.@.@.@.@.@.@.@.@.@._ f.i .       ",
	"      u f.$.$.$.$.$.$.$.$.$.$.$.%.%.$.$.$.$.$.$.%.$.f.y .       ",
	"      r f.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.f.t .       ",
	"      w f.*.*.*.*.*.*.*.*.*.*.*.=.*.*.*.*.*.*.*.=.*.f.e .       ",
	"      q f.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.f.q .       ",
	"      9 f.;.;.;.:.:.;.:.:.;.;.;.;.>.:.;.;.;.;.;.>.;.f.0 .       ",
	"      8 f.<.,.,.,.,.,.,.,.,.,.,.,.,.,.,.<.,.,.,.<.<.f.8 .       ",
	"      6 f.3.3.3.3.3.3.3.3.4.3.3.3.4.3.4.3.3.4.3.3.3.f.7 .       ",
	"      5 f.6.7.6.6.8.6.6.8.6.9.6.6.6.6.6.6.6.6.6.6.6.f.5 .       ",
	"      3 f.0.0.0.0.q.0.0.q.0.0.0.0.0.0.0.0.0.0.0.0.0.f.4 .       ",
	"      2 f.w.w.w.w.w.w.w.w.w.w.w.w.w.w.e.w.w.w.w.w.w.f.2 .       ",
	"      1 f.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.f.< .       ",
	"      > f.t.t.t.t.t.t.t.t.t.t.y.t.t.t.t.t.t.t.t.t.t.f., .       ",
	"      : f.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.f.: .       ",
	"      - f.p.i.i.i.p.i.i.p.i.i.i.i.i.i.i.i.i.i.i.i.i.f.; .       ",
	"      = f.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.f.* .       ",
	"      & f.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.f.% .       ",
	"      # f.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.f.$ .       ",
	"      @ f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.+ .       ",
	"      o f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.O .       ",
	"      X X X X X X X X X X X X X X X X X X X X X X X X X .       ",
	"          . . . . . . . . . . . . . . . . . . . . . . .         "
};

const char *Ikonki::zapisz[] = {
	/* columns rows colors chars-per-pixel */
	"32 32 61 1 ",
	"  c black",
	". c #646464",
	"X c gray47",
	"o c #234394",
	"O c #2B4C9A",
	"+ c #6685BA",
	"@ c #549ACE",
	"# c #589CCF",
	"$ c #5C9ED0",
	"% c #64A4D3",
	"& c #6CA9D5",
	"* c #72ACD7",
	"= c #77AEDA",
	"- c #78AEDA",
	"; c #7DB1DB",
	": c #838383",
	"> c #979797",
	", c #ABAAAB",
	"< c #B2B2B2",
	"1 c #BBBABB",
	"2 c #8CA8CE",
	"3 c #95AFD2",
	"4 c #82B4DC",
	"5 c #86B8DE",
	"6 c #8AB9DE",
	"7 c #9BB5D7",
	"8 c #8DBCE1",
	"9 c #92BFE2",
	"0 c #95C1E4",
	"q c #9BC4E5",
	"w c #9FC6E8",
	"e c #A2C6E4",
	"r c #A9CAE6",
	"t c #A5C9E9",
	"y c #ADCDE9",
	"u c #B4D1EB",
	"i c #BCD6EC",
	"p c #BFD8EE",
	"a c #C3C3C3",
	"s c #CBCBCB",
	"d c #D4D4D4",
	"f c gray86",
	"g c #C0D7EC",
	"h c #C3DAEE",
	"j c #C9DCED",
	"k c #C6DCF0",
	"l c #CADEF1",
	"z c #CEE1F3",
	"x c #CCE3F9",
	"c c #D3E4F4",
	"v c #D8E7F5",
	"b c #D2E6F9",
	"n c #D6E8FA",
	"m c #DBEBFB",
	"M c #E1EEFB",
	"N c #E6F1FC",
	"B c #EBF4FD",
	"V c #F0F6FD",
	"C c #F4F9FE",
	"Z c #FEFEFF",
	"A c None",
	/* pixels */
	"AAAAAAAXXXXXXXXXXXXXXXXXXAAAAAAA",
	"AAAAAAAX,,,<<<1aassddfffXAAAAAAA",
	"AAAooooX,,,<<11aass>:.ffXooooAAA",
	"AAo7vvvX,,,,<11aass>:.ffXvcc2oAA",
	"Ao3vvvvX,,,<<11aass>:.ffXczcz+oA",
	"AocvvccX,,,<<11aass>:.ffXzzczzOA",
	"AovzcvcX,,,<<11aass>:.ffXzzlzzo ",
	"AoccczzX,,,<<11asss>:.ffXlllllo ",
	"AozczczX,,,<<11aassddfffXlkkkko ",
	"AozzzzzXXXXXXXXXXXXXXXXXXkkkkpo ",
	"Aozllllllljllkkkhkkhhhhhhhhpppo ",
	"Aollkkkkkkjhkhhkhhhhhipppppippo ",
	"Aohkhhhkhhhhhghipiuuyttwwqqqwko ",
	"Aohgh$$$$$$$$$$$$$$$$$$$$$$q0po ",
	"Aogig$ZZZZZZZZZZZZZZZZZZZZ$00po ",
	"Aoiii$ZZZZZCCCCVVBBNNMmmmZ$99uo ",
	"Aouuu#ZZZZZCCVVVVBNNNmmmnZ$88uo ",
	"Aoyyy#ZZZZCZCVVVBNNMmmmmnZ$88yo ",
	"Aorre$ZZhhjhjhigiiiuuuuunZ$55ro ",
	"Aoe06$ZZCZCVVVBBNNMmmnnnbZ$44eo ",
	"Aor4;$ZZZZCCVVBNNMmmmmnbbZ$;;eo ",
	"Aoe-=$ZZggggiiiiuiuuuyyrbZ$==eo ",
	"Aoe**$ZCCCCVVBNNMMmmnnbbxZ$**eo ",
	"Aoe&&$ZZCCVBVNNMMmmmnbbbxZ$&&eo ",
	"Aoe%%$ZChggiiiiuuuyuyyrtxZ$%%eo ",
	"Aoe%%$ZCVVVBNMMMmmnnbnxxxZ$%%eo ",
	"Aor#$$ZCVVBBNMMmmnnbxxxxxZ$$$eo ",
	"Aoe##$ZZZZZZZZZZZZZZZZZZZZ$##eo ",
	"Aoe###$$$$$$$$$$$$$$$$$$$$$@@eo ",
	"Aoeeeeeeeeeeeeeeeeeeeeeeeeeeeeo ",
	"Aoooooooooooooooooooooooooooooo ",
	"AAA                            A"
};

const char *Ikonki::otworz[] = {
	/* columns rows colors chars-per-pixel */
	"32 32 203 2 ",
	"   c #000000",
	".  c #080600",
	"X  c #110D01",
	"o  c #302402",
	"O  c #392B02",
	"+  c #443303",
	"@  c #014201",
	"#  c #025402",
	"$  c #015B01",
	"%  c #304605",
	"&  c #2B5809",
	"*  c #036703",
	"=  c #036B03",
	"-  c #086A08",
	";  c #126901",
	":  c #057E05",
	">  c #0D760B",
	",  c #087B08",
	"<  c #12790D",
	"1  c #1E6113",
	"2  c #147F14",
	"3  c #1A7912",
	"4  c #326E09",
	"5  c #3B7603",
	"6  c #2D7311",
	"7  c #5B4403",
	"8  c #654A03",
	"9  c #6E5104",
	"0  c #74590B",
	"q  c #715E13",
	"w  c #406501",
	"e  c #547A03",
	"r  c #7D6106",
	"t  c #7C6713",
	"y  c #717F16",
	"u  c #505627",
	"i  c #477B32",
	"p  c #706640",
	"a  c #846100",
	"s  c #8B6704",
	"d  c #8A6802",
	"f  c #926C05",
	"g  c #9F7D07",
	"h  c #0A8006",
	"j  c #0E8409",
	"k  c #0B8B09",
	"l  c #178609",
	"z  c #1B880C",
	"x  c #0D940D",
	"c  c #148214",
	"v  c #188618",
	"b  c #1C8C1C",
	"n  c #109E10",
	"m  c #258307",
	"M  c #21941A",
	"N  c #13A213",
	"B  c #16AB16",
	"V  c #18AE18",
	"C  c #19B219",
	"Z  c #229522",
	"A  c #27B427",
	"S  c #30A730",
	"D  c #34AC34",
	"F  c #3FA63F",
	"G  c #39BD39",
	"H  c #4B8508",
	"J  c #40A740",
	"K  c #50B750",
	"L  c #53BF53",
	"P  c #5EBC5E",
	"I  c #4AC24A",
	"U  c #54C454",
	"Y  c #5CC15C",
	"T  c #5AC95A",
	"R  c #61CB61",
	"E  c #6BCC6B",
	"W  c #74CD74",
	"Q  c #72D172",
	"!  c #7CD37C",
	"~  c #9E9202",
	"^  c #AD8005",
	"/  c #AD8708",
	"(  c #B58606",
	")  c #B88700",
	"_  c #BD9107",
	"`  c #B99901",
	"'  c #BC9208",
	"]  c #AA8C19",
	"[  c #B38710",
	"{  c #B5961D",
	"}  c #9DA103",
	"|  c #B29A20",
	" . c #CB8C03",
	".. c #C69407",
	"X. c #CB9504",
	"o. c #C79802",
	"O. c #CC9A07",
	"+. c #C39608",
	"@. c #CA9708",
	"#. c #CC9A09",
	"$. c #D29706",
	"%. c #D59C03",
	"&. c #D29E09",
	"*. c #C6A903",
	"=. c #D7A104",
	"-. c #DAA304",
	";. c #D3A108",
	":. c #DAA608",
	">. c #DDAB09",
	",. c #C7A318",
	"<. c #DCA814",
	"1. c #DAB51F",
	"2. c #E6A505",
	"3. c #EFA50B",
	"4. c #E0AC08",
	"5. c #EBAA0D",
	"6. c #F5A606",
	"7. c #FCA602",
	"8. c #F6AC02",
	"9. c #FCAA02",
	"0. c #E6B30D",
	"q. c #E9B509",
	"w. c #FEB403",
	"e. c #FEBB03",
	"r. c #F1BF0B",
	"t. c #E5AC13",
	"y. c #EBAB14",
	"u. c #EFBE12",
	"i. c #E4B219",
	"p. c #E7BF1E",
	"a. c #EDBD1D",
	"s. c #C7A72A",
	"d. c #DEAE25",
	"f. c #DBB92B",
	"g. c #E7BF33",
	"h. c #E6BB3E",
	"j. c #FEC504",
	"k. c #FECB05",
	"l. c #FDCD0E",
	"z. c #FFD10C",
	"x. c #F7C917",
	"c. c #FECF13",
	"v. c #F5CD19",
	"b. c #FCCF1C",
	"n. c #FFD115",
	"m. c #FED11C",
	"M. c #EBC323",
	"N. c #EFC828",
	"B. c #F5C721",
	"V. c #F6CB21",
	"C. c #FED223",
	"Z. c #FED42C",
	"A. c #EAC233",
	"S. c #F5CE35",
	"D. c #FFD633",
	"F. c #FFDA33",
	"G. c #FED73A",
	"H. c #FFD83E",
	"J. c #9B8942",
	"K. c #9C9244",
	"L. c #879E5B",
	"P. c #B8A65F",
	"I. c #B5AA7E",
	"U. c #D0BC6B",
	"Y. c #DEC655",
	"T. c #ECC047",
	"R. c #FFCF4B",
	"E. c #F9D443",
	"W. c #FFD944",
	"Q. c #FFDB4B",
	"!. c #E5C655",
	"~. c #EECA53",
	"^. c #FFD753",
	"/. c #FFDC52",
	"(. c #FFDD5D",
	"). c #F4D362",
	"_. c #FEDF65",
	"`. c #FFDD69",
	"'. c #FFDE70",
	"]. c #FFE374",
	"[. c #FFE47B",
	"{. c #83D683",
	"}. c #DED199",
	"|. c #EED986",
	" X c #F3D882",
	".X c #E6D69A",
	"XX c #FFE683",
	"oX c #FEE68B",
	"OX c #FFE88E",
	"+X c #F8E096",
	"@X c #FFEA93",
	"#X c #FAE599",
	"$X c #FFEB9D",
	"%X c #FBE7A2",
	"&X c #FFECA4",
	"*X c #FEEDAB",
	"=X c #FFF0A2",
	"-X c #FFF3AE",
	";X c #FFEFB1",
	":X c #FFF0B6",
	">X c #FFF2BB",
	",X c #FFF4C4",
	"<X c None",
	/* pixels */
	"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
	"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
	"<X<X<X<X<X<X<X<X<X<X<X<X<X<Xv b Z b c > <X<X<X<X<X<X<X<X<X<X<X<X",
	"<X<X<X<X<X<X<X<X<X<X<X<X, b J P ! {.E K Z * <X<X<X<X<X<X<X<X<X<X",
	"<X<X<X<X<X<X<X<X<X<X<X<Xc - $ $ J W {.! ! S = <X<X<X<X<X<X<X<X<X",
	"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X@ 2 Y Q E T n $ <X<X<X<X<X<X<X<X",
	"<X<X<X<X<X:.>.>.>.>.:./ <X<X<X<X<X<X2 L R U V h <X<X<X<X<X<X<X<X",
	"<X<X<X<X>.).:X;X*X$XoXA.g <X<X<X<X<X<Xb U I V x # <X<X<X<X<X<X<X",
	"<X<X<X<X>.&X&X$X@XoX[.`.:.O.;.;.;.;.+.5 D G B n ; r ' <X<X<X<X<X",
	"<X<X<X<X>.@X@XXX'._.R.k.k.k.k.k.k.k.k.} M A B n ; s _ <X<X<X<X<X",
	"<X<X<X<X>.[.`.R.k.k.k.k.k.j.j.k.k.j.j.*.z C B B j w e = * <X<X<X",
	"<X<X<X<X>.^.k.k.k.k.j.e.e.e.e.w.w.w.9.o.l C V B n k x k @ <X<X<X",
	"<X<X<X<X:.k.k.j.j.e.w.9.9.7.7.7.%.` ~ m B C C C B N x #   <X<X<X",
	"<X<X<X<X>.k.j.e.w.7.7.6.6.3.5.t.<.H j B C C C C B N h % 0 [ O.<X",
	"<X<X<X<X:.j.e.w.9.6.y.T.#X%X%X*X%X.XL.3 x B C B N x 1 p P.!.) <X",
	"<X<X<X<X$.e.8.2.h.+X,X,X,X:X:X;X;X*X}.I.i < N B N > u J.Y.A.a <X",
	"<X<X<X<X$. .d. X,X,X>X:X;X*X&X&X&X$X#X|.U.K.6 j k & t ,.v.0.7 <X",
	"<X<X<X<X:.%.#X,X:X:X;X*X&X&X$X@XXX].(./.E.A.s.y 4 q ] p.m.>.o <X",
	"<X<X<X<X:.;.-X*X*X*X&X&X&XOX[._./.Q.W.W.W.G.S.f.| { 1.V.m.#.  <X",
	"<X<X<X<X>.d.-X=X$X$X$XOX].(./././.Q.W.W.H.G.D.Z.N.M.V.b.x.^   <X",
	"<X<X<X<X:.h.=X@X@XoX].(.^./.Q.Q.Q.W.W.H.G.D.D.Z.C.C.m.m.u.s <X<X",
	"<X<X<X<X=.~.OXXX[.(./.Q.^.Q.Q.Q.W.W.H.G.D.D.Z.Z.C.C.m.m.0.8 <X<X",
	"<X<X<X<X=.).[._./.Q.Q.Q.Q.W.W.W.W.H.G.D.D.Z.Z.C.C.m.b.n.>.O <X<X",
	"<X<X<X<X=._.(.W.W.W.W.W.W.W.H.H.G.F.D.Z.Z.Z.C.m.m.m.n.n.;.. <X<X",
	"<X<X<X<X<./.H.H.H.H.H.H.H.G.G.D.D.D.Z.Z.C.C.m.m.n.n.c.l.(   <X<X",
	"<X<X<X<Xi.H.F.G.G.G.G.G.D.D.D.D.Z.Z.Z.C.C.C.m.b.n.c.z.r.f <X<X<X",
	"<X<X<XX.a.F.D.D.D.D.D.D.D.Z.Z.Z.Z.C.C.C.m.m.n.n.c.l.z.q.9 <X<X<X",
	"<X<X<XO.B.Z.Z.Z.Z.Z.Z.Z.Z.Z.C.C.C.C.m.b.b.n.c.c.z.z.z.4.+ <X<X<X",
	"<X<X<X&.;.O.#.#.#.#.#.#.#.#.#.#.O.O.O.O.O.O.O.O.O.O.O.+.X <X<X<X",
	"<X<X<X<X<X                                              <X<X<X<X",
	"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
	"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X"
};

const char *Ikonki::usuwanie[] = {
	"32 32 2 1",
	" 	c #F0F0F0",
	".	c #E70000",
	"                                ",
	"                                ",
	"  .....                  .....  ",
	"  ......                ......  ",
	"  .......              .......  ",
	"  ........            ........  ",
	"  .........          .........  ",
	"   .........        .........   ",
	"    .........      .........    ",
	"     .........    .........     ",
	"      .........  .........      ",
	"       ..................       ",
	"        ................        ",
	"         ..............         ",
	"          ............          ",
	"           ..........           ",
	"           ..........           ",
	"          ............          ",
	"         ..............         ",
	"        ................        ",
	"       ..................       ",
	"      .........  .........      ",
	"     .........    .........     ",
	"    .........      .........    ",
	"   .........        .........   ",
	"  .........          .........  ",
	"  ........            ........  ",
	"  .......              .......  ",
	"  ......                ......  ",
	"  .....                  .....  ",
	"                                ",
	"                                "
};

const char *Ikonki::start[] = {
	"32 32 3 1",
	" 	c None",
	".	c #F0F0F0",
	"+	c #00CD00",
	"................................",
	"................................",
	"..++++++++++++++................",
	"..+++++++++++++++...............",
	"..++.++.++.++.++++..............",
	"..++.++.++.++.+++++.............",
	"..++.++.++.++.++++++............",
	"..++.++.++.++.+++++++...........",
	"..++.++.++.++.++++++++..........",
	"..++.++.++.++.+++++++++.........",
	"..++.++.++.++.++++++++++........",
	"..++.++.++.++.+++++++++++.......",
	"..++.++.++.++.++++++++++++......",
	"..++.++.++.++.+++++++++++++.....",
	"..++.++.++.++.++++++++++++++....",
	"..++.++.++.++.+++++++++++++++...",
	"..++.++.++.++.+++++++++++++++...",
	"..++.++.++.++.++++++++++++++....",
	"..++.++.++.++.+++++++++++++.....",
	"..++.++.++.++.++++++++++++......",
	"..++.++.++.++.+++++++++++.......",
	"..++.++.++.++.++++++++++........",
	"..++.++.++.++.+++++++++.........",
	"..++.++.++.++.++++++++..........",
	"..++.++.++.++.+++++++...........",
	"..++.++.++.++.++++++............",
	"..++.++.++.++.+++++.............",
	"..++.++.++.++.++++..............",
	"..+++++++++++++++...............",
	"..++++++++++++++................",
	"................................",
	"................................"
};